In [272]:
import pandas as pd 
import numpy as np 
# np.random()
n_rows=1000
data={'color':np.random.choice(['red','blue','green'],n_rows),
      'size': np.random.choice(['small','medium','large'],n_rows),
      'material':np.random.choice(['plastic','metal','wood'],n_rows),
      'price': np.random.randint(10,500,n_rows)}
df=pd.DataFrame(data)


In [273]:
df

,color,size,material,price
0,blue,medium,plastic,321
1,red,medium,metal,395
2,green,large,wood,303
3,blue,small,wood,266
4,blue,large,metal,176
...,...,...,...,...
995,red,small,plastic,422
996,green,small,plastic,490
997,red,large,wood,132
998,blue,small,wood,29


In [274]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, OrdinalEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from category_encoders import TargetEncoder

In [275]:
X=df.drop(columns='price')
Y=df['price']
Xtrain,Xtest,Ytrain,Ytest=train_test_split(X,Y,train_size=0.8,random_state=42)

In [276]:
label_encoder=LabelEncoder()
'''updated_xtrain=label_encoder.fit_transform(Xtrain)
ValueError("y should be a 1d array, got an array of shape {} instead.".format(shape))
   '''

'updated_xtrain=label_encoder.fit_transform(Xtrain)\nValueError("y should be a 1d array, got an array of shape {} instead.".format(shape))\n   '

In [277]:
label_encoder.fit_transform(Xtrain['color'])

array([1, 1, 2, 1, 0, 2, 1, 0, 0, 0, 2, 2, 1, 1, 1, 2, 2, 1, 2, 0, 2, 1,
       2, 0, 1, 1, 2, 1, 1, 0, 2, 2, 1, 2, 1, 2, 1, 2, 0, 0, 0, 0, 1, 1,
       0, 1, 2, 0, 1, 0, 0, 2, 2, 0, 1, 2, 0, 0, 1, 2, 2, 0, 0, 1, 1, 1,
       2, 1, 1, 2, 1, 0, 1, 1, 0, 1, 1, 1, 2, 2, 2, 1, 0, 0, 2, 1, 1, 1,
       0, 1, 0, 2, 1, 1, 0, 1, 0, 2, 1, 2, 1, 2, 2, 2, 1, 0, 0, 1, 2, 1,
       0, 2, 1, 2, 0, 0, 1, 0, 2, 2, 1, 0, 1, 0, 0, 0, 0, 2, 2, 0, 1, 2,
       0, 2, 0, 2, 0, 1, 2, 0, 2, 2, 1, 1, 2, 1, 2, 1, 2, 1, 1, 2, 2, 1,
       2, 1, 1, 1, 1, 0, 2, 0, 1, 1, 2, 1, 1, 2, 0, 0, 1, 2, 2, 2, 2, 1,
       1, 0, 1, 1, 2, 1, 0, 0, 1, 0, 0, 1, 0, 1, 2, 0, 1, 0, 1, 0, 0, 2,
       1, 2, 1, 0, 0, 2, 2, 1, 2, 0, 0, 1, 2, 2, 0, 2, 0, 1, 2, 0, 2, 1,
       1, 0, 1, 0, 0, 2, 1, 2, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 2, 2, 0,
       1, 2, 0, 1, 2, 0, 2, 1, 2, 2, 2, 1, 2, 0, 2, 1, 0, 1, 2, 2, 2, 1,
       2, 0, 0, 0, 2, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 2, 1, 2, 0,
       2, 1, 2, 2, 2, 0, 0, 1, 0, 1, 0, 2, 0, 0, 1,

In [278]:
one_hot_encoder=OneHotEncoder(sparse_output=False)
# one_hot_encoder.fit_transform(Xtrain)
values=one_hot_encoder.fit_transform(Xtrain)
# values=values.toarray()
values

array([[0., 1., 0., ..., 1., 0., 0.],
       [0., 1., 0., ..., 0., 0., 1.],
       [0., 0., 1., ..., 1., 0., 0.],
       ...,
       [0., 0., 1., ..., 0., 1., 0.],
       [0., 0., 1., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 0., 1.]])

In [279]:
columns=one_hot_encoder.get_feature_names_out()

In [280]:
pd.DataFrame(values,columns=columns).astype(int)

,color_blue,color_green,color_red,size_large,size_medium,size_small,material_metal,material_plastic,material_wood
0,0,1,0,0,0,1,1,0,0
1,0,1,0,0,0,1,0,0,1
2,0,0,1,1,0,0,1,0,0
3,0,1,0,0,1,0,0,1,0
4,1,0,0,0,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...
795,0,1,0,0,0,1,0,1,0
796,0,0,1,0,1,0,0,0,1
797,0,0,1,0,1,0,0,1,0
798,0,0,1,1,0,0,0,1,0


In [281]:
'''one_hot_encoder.transform(Xtest['color'])  Expected a 2-dimensional container but got <class 'pandas.core.series.Series'> instead'''
'''one_hot_encoder.transform(Xtest[['color','size']]) ValueError: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- material
'''

"one_hot_encoder.transform(Xtest[['color','size']]) ValueError: The feature names should match those that were passed during fit.\nFeature names seen at fit time, yet now missing:\n- material\n"

In [282]:
'''
new_input=[['red','large'],['blue','small']]
one_hot_encoder.transform(new_input)  #ValueError: X has 2 features, but OneHotEncoder is expecting 3 features as input.
'''

'''new_input=[['red1','large','plastic'],['blue','small','wood']]
one_hot_encoder.transform(new_input)
ValueError: Found unknown categories ['red1'] in column 0 during transform
'''



"new_input=[['red1','large','plastic'],['blue','small','wood']]\none_hot_encoder.transform(new_input)\nValueError: Found unknown categories ['red1'] in column 0 during transform\n"

In [283]:
one_hot_encoder=OneHotEncoder(sparse_output=False,  handle_unknown='ignore')
updated_xtrain=one_hot_encoder.fit_transform(Xtrain)
new_input=[['red1','large','plastic'],['blue','small','wood']]
one_hot_encoder.transform(new_input)


c:\Users\91789\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[0., 0., 0., 1., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 1., 0., 0., 1.]])

- if label is not present then it assigns zero - for this we need to use handle_unknown='ignore'(By default it will be 'error') It ignores the errors

In [284]:
one_hot_encoder.get_feature_names_out()

array(['color_blue', 'color_green', 'color_red', 'size_large',
       'size_medium', 'size_small', 'material_metal', 'material_plastic',
       'material_wood'], dtype=object)

In [285]:
from sklearn.preprocessing import OrdinalEncoder

In [286]:
Ordi_encoder=OrdinalEncoder()
Ordi_encoder.fit_transform(Xtrain)


'''Ordi_encoder.fit_transform(Xtrain['color']) 
Expected a 2-dimensional container but got <class 'pandas.core.series.Series'> instead.
Pass a DataFrame containing a single row.
'''
'''Ordi_encoder.transform(Xtest['color'])
'Ordi_encoder.fit_transform(Xtest['color']) 
Expected a 2-dimensional container but got <class 'pandas.core.series.Series'> instead.
Pass a DataFrame containing a single row.'''



"Ordi_encoder.transform(Xtest['color'])\n'Ordi_encoder.fit_transform(Xtest['color']) \nExpected a 2-dimensional container but got <class 'pandas.core.series.Series'> instead.\nPass a DataFrame containing a single row."

In [287]:
Ordi_encoder.get_feature_names_out()

array(['color', 'size', 'material'], dtype=object)

In [288]:
'''
new_input=[['gold','medium','metal']]
Ordi_encoder.transform(new_input)
ValueError: Found unknown categories ['gold'] in column 0 during transform'''

"\nnew_input=[['gold','medium','metal']]\nOrdi_encoder.transform(new_input)\nValueError: Found unknown categories ['gold'] in column 0 during transform"

In [289]:
ord_encoder=OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1)

In [290]:

ord_encoder.fit_transform(Xtrain)
new_input=[['gold','medium','metal'], ['red','large','wood']]
ord_encoder.transform(new_input)

c:\Users\91789\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(


array([[-1.,  1.,  0.],
       [ 2.,  0.,  2.]])

In [291]:
# to remove the warning in the above cell
new_data=pd.DataFrame(data=[['gold','medium','metal'], ['red','large','wood']], columns=['color','size','material'])
ord_encoder.transform(new_data)

array([[-1.,  1.,  0.],
       [ 2.,  0.,  2.]])

In [292]:
'''o_encoder=OrdinalEncoder(categories=[['green','blue','red']],handle_unknown='use_encoded_value',unknown_value=-1)
o_encoder.fit_transform(Xtrain) 
#ValueError: Shape mismatch: if categories is an array, it has to be of shape (n_features,)
Here we have passed only one column order but we have to mention all columns order or else it will throw value error due to shape mismatch.
'''

"o_encoder=OrdinalEncoder(categories=[['green','blue','red']],handle_unknown='use_encoded_value',unknown_value=-1)\no_encoder.fit_transform(Xtrain) \n#ValueError: Shape mismatch: if categories is an array, it has to be of shape (n_features,)\nHere we have passed only one column order but we have to mention all columns order or else it will throw value error due to shape mismatch.\n"

In [293]:
o_encoder=OrdinalEncoder(categories=[['green','blue','red'],['medium','small','large'],['wood','plastic','metal']],
                         handle_unknown='use_encoded_value',unknown_value=-1) # here all columns order have been mentioned so it works properly
o_encoder.fit_transform(Xtrain)
o_encoder.transform(Xtest)
new_input=pd.DataFrame([['red','small','metal']],columns=Xtrain.columns)
o_encoder.transform(new_input) #array([[2., 1., 2.]]) # transform also accepts 2D.
# so it is arranging based on the order .

array([[2., 1., 2.]])

In [294]:
o_encoder=OrdinalEncoder(categories=[['green1','blue','red'],['medium','small','large'],['wood','plastic','metal']],
                         handle_unknown='use_encoded_value',unknown_value=-1) 
# when we are passing unknown value in the categories order it assigns -1 for the value which we have not mentioned 
o_encoder.fit_transform(Xtrain)

array([[-1.,  1.,  2.],
       [-1.,  1.,  0.],
       [ 2.,  2.,  2.],
       ...,
       [ 2.,  0.,  1.],
       [ 2.,  2.,  1.],
       [-1.,  1.,  0.]])

In [295]:
'''o_encoder=OrdinalEncoder(categories=[['green1','blue','red'],['wood','plastic','metal'],['medium','small','large']])
o_encoder.fit_transform(Xtrain) 
#ValueError: Found unknown categories ['green'] in column 0 during fit'''

"o_encoder=OrdinalEncoder(categories=[['green1','blue','red'],['wood','plastic','metal'],['medium','small','large']])\no_encoder.fit_transform(Xtrain) \n#ValueError: Found unknown categories ['green'] in column 0 during fit"

In [296]:
'''o_encoder=OrdinalEncoder(categories=[['green1','blue','red'],['wood','plastic','metal'],['medium','small','large']], handle_unknown='use_encoded_value')
o_encoder.fit_transform(Xtrain) 
#TypeError: unknown_value should be an integer or np.nan when handle_unknown is 'use_encoded_value', got None.'''

"o_encoder=OrdinalEncoder(categories=[['green1','blue','red'],['wood','plastic','metal'],['medium','small','large']], handle_unknown='use_encoded_value')\no_encoder.fit_transform(Xtrain) \n#TypeError: unknown_value should be an integer or np.nan when handle_unknown is 'use_encoded_value', got None."

In [297]:
from category_encoders import TargetEncoder
t_encoder=TargetEncoder(cols='color', handle_unknown='values') 
#we can use this cols parameter when we have mixed columns 
#handle_unkown solves the error, when we have unknown values then, it will transform by finding the average of all the target columns (ytrain)

In [298]:
'''t_encoder.fit_transform(Xtrain) #TypeError: fit_transform() missing argument: y'''

't_encoder.fit_transform(Xtrain) #TypeError: fit_transform() missing argument: y'

In [299]:
t_encoder.fit_transform(Xtrain,Ytrain) 
#when we have more unique values we can use this target encoder and we apply this for only categorical columns 

,color,size,material
29,256.333333,small,metal
535,256.333333,small,wood
695,259.795082,large,metal
557,256.333333,medium,plastic
836,250.098113,medium,metal
...,...,...,...
106,256.333333,small,plastic
270,259.795082,medium,wood
860,259.795082,medium,plastic
435,259.795082,large,plastic


In [300]:
obj_cols=Xtrain.select_dtypes(include='object')
#to select particular type of column which is required like for example here 
# above we have used include paramenter inside select_dtypes to include only the object columns.
num_cols=Xtrain.select_dtypes(include='int')
obj_cols

,color,size,material
29,green,small,metal
535,green,small,wood
695,red,large,metal
557,green,medium,plastic
836,blue,medium,metal
...,...,...,...
106,green,small,plastic
270,red,medium,wood
860,red,medium,plastic
435,red,large,plastic


In [301]:
t_encoder.transform(Xtest)

,color,size,material
521,250.098113,large,plastic
737,259.795082,large,plastic
740,259.795082,large,metal
660,256.333333,large,wood
411,256.333333,large,plastic
...,...,...,...
408,256.333333,small,metal
332,256.333333,medium,metal
208,259.795082,large,metal
613,250.098113,small,plastic


In [302]:
# new_input=[['red','medium','metal']]
#KeyError: 'color' , it returns key error because we need to pass the new values along with the column names also 
# t_encoder.transform(new_input)

In [303]:
# new_input = pd.DataFrame([['red', 'medium', 'metal']],columns=Xtrain.columns)
new_input=pd.DataFrame({'color':['red'],'size':['medium'],'material':['wood']})

In [304]:
t_encoder.transform(new_input)

,color,size,material
0,259.795082,medium,wood
